<a href="https://colab.research.google.com/github/yaong0915/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 6강 - 데이터 전처리 1

### 6-1 데이터 훑어보기

In [ ]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

# 데이터 측정
df.describe()
# 모든 데이터 타입 측정
df.describe(include='all')
# 수치형 데이터 측정
df.describe(include=[np.number])
# 범주형 데이터 측정
df.describe(include=['object'])
# 특정 열 분석
df['score'].describe()

count     4.000000
mean     87.500000
std       6.454972
min      80.000000
25%      83.750000
50%      87.500000
75%      91.250000
max      95.000000
Name: score, dtype: float64

In [48]:
import pandas as pd

## 데이터 수집 url 및 api key 설정
url ='https://apis.data.go.kr/B552845/perDay/price'
api_key ='c4592c52bd73301355fcda3fc00038fe7755d444df6fda681a82a33adde604cc'
params ={
    'serviceKey': api_key ,
    'pageNo':'1',
    'numOfRows':'100',
    'cond[exmn_ymd::GTE]':'20150101',
    'cond[exmn_ymd::LTE]':'20241231',
    'cond[se_cd::EQ]':'02',
    'cond[ctgry_cd::EQ]':'200',
    'cond[item_cd::EQ]':'211',
    ##'cond[vrty_cd::EQ]':'01',
    ##'cond[grd_cd::EQ]':'04',
   'cond[sgg_cd::EQ]':'1101',
    'cond[mrkt_cd::EQ]':'0110211',
    'returnType':'JSON',
    ##'selectable':'item_cd,vrty_cd',
}
## 데이터 수집


response =requests.get (url ,params =params )

## 호출 성공/실패 출력
print (response.json ())

{'response': {'body': {'dataType': 'JSON', 'items': {'item': [{'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150102', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-02T13:57:56Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '03', 'vrty_nm': '가을'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150102', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-02T13:57:56Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '03', 'vrty_nm': '가을'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150105', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-05T14:20:57Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '03', 'vrty_nm': '가을'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150105', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-05T14:20:57Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '03', 'vrty_nm': '가을'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150106', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-06T13:49:28Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '03', 'vrty_nm': '가을'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150106', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-06T13:49:28Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '03', 'vrty_nm': '가을'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150107', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-07T13:49:11Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150107', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-07T13:49:11Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150108', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-08T13:50:57Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150108', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-08T13:50:57Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150109', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-09T14:00:03Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150109', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-09T14:00:03Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150112', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-12T13:46:35Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150112', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-12T13:46:35Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150113', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-13T13:50:54Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150113', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-13T13:50:54Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150114', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-14T13:49:28Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150114', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-14T13:49:28Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150115', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-15T13:49:48Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150115', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-15T13:49:48Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150116', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-16T13:57:58Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150116', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-16T13:57:58Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150119', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-19T13:43:04Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150119', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-19T13:43:04Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150120', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-20T13:57:39Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150120', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-20T13:57:39Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150121', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-21T14:00:21Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150121', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-21T14:00:21Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150122', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-22T13:47:44Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150122', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-22T13:47:44Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150123', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-23T13:45:56Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150123', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-23T13:45:56Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150126', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-26T13:53:54Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150126', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-26T13:53:54Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150127', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-27T13:52:43Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150127', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-27T13:52:43Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150128', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-28T13:42:55Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150128', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-28T13:42:55Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150129', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-29T14:00:28Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150129', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-29T14:00:28Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150130', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-30T14:44:10Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150130', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-01-30T14:44:10Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150202', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-02-02T14:06:01Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150202', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-02-02T14:06:01Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150203', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-02-03T13:57:52Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150203', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-02-03T13:57:52Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150204', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-02-04T13:51:44Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150204', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-02-04T13:51:44Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '4000', 'exmn_dd_prc': '4000', 'exmn_ymd': '20150205', 'grd_cd': '04', 'grd_nm': '상품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2015-02-05T14:09:56Z', 'se_cd': '02', 'se_nm': '중도매', 'sgg_cd': '1101', 'sgg_nm': '서울', 'unit': 'kg(그물망 3포기)', 'unit_sz': '10', 'vrty_cd': '06', 'vrty_nm': '월동'}, {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_dd_cnvs_prc': '3000', 'exmn_dd_prc': '3000', 'exmn_ymd': '20150205', 'grd_cd': '05', 'grd_nm': '중품', 'item_cd': '211', 'item_nm': '배추', 'mrkt_cd': '0110211', 'mrkt_nm': '가락도매', 'orgnl_reg_dt': '2

In [53]:
import pandas as pd
## requests로부터 response, body, item 항목 읽기
itms=response.json()['response']['body']['items']

df=pd.DataFrame(itms)
print(type(df))
print(len(df))
print(df.head())
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
100
                                                item
0  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
1  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
2  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
3  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
4  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   item    100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes
None

                                                 item
0   {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
1   {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
2   {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
3   {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
4   {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
..                                                ...
95  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
96  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
97  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
98  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...
99  {'ctgry_cd': '200', 'ctgry_nm': '채소류', 'exmn_d...

[100 rows x 1 columns]

In [51]:
import pandas as pd
df['exmn_dd_prc']= pd.to_numeric(df['exmn_dd_prc'])
df['exmn_ymd']= pd.to_datetime(df['exmn_ymd'].astype(str))
df['year']= df['exmn_ymd'].dt.year
df['month']= df['exmn_ymd'].dt.month
df['day']= df['exmn_ymd'].dt.day
print(df[['exmn_ymd', 'year', 'month', 'day', 'exmn_dd_prc']].head())

KeyError: 'exmn_dd_prc'

### 6-2 DataFrame 열 선택 및 **조작**

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

# 특정 열 선택
selected_col=df[['이름','학과','학점']]
selected_col
# DataFrame 열순서 변경
selected_cols=df[['학과','이름','학년','학점','동아리']]
selected_cols
# DataFrame 열이름 변경
df_renamed=df.rename(columns={'이름':'학생명','학점':'평점','동아리':'과외활동'})
df_renamed

   학생명  학년   평점     학과   과외활동
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

### 6-3 DataFrame 행 선택

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정
df=pd.DataFrame(data)
df=df.set_index('이름')
df
#DataFrame 행 선택
df.loc['김철수']
df.loc[['김철수','이영희']]
df.loc['김철수':'박민수']
#DataFrame 위치 기반 행 선택
df.iloc[1]
df.iloc[[1,3]]
df.iloc[0:3]
#DataFrame 조건 기반 선택
df
df.loc[[True,False,True,False,False]]
df['학점']>=4.2
df.loc[df['학점']>=4.2]
df.loc[df['학년']==2]
df.loc[(df['학년']==2)&(df['학점']>=3.0)]

     학년   학점   학과   동아리
이름
이영희   2  3.8  경영학  독서토론
정소희   2  3.5  심리학  음악감상

### 6-4 DataFrame 정렬

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정
df=pd.DataFrame(data).set_index('이름')
df
#DataFrame 단일 열 오름차순, 내림차순 정렬
df.sort_values(by='학점')
df.sort_values(by='학년',ascending=False)
#DataFrame 복수 열 오름차순, 내림차순 정렬
df.sort_values(by=['학년','학점'],ascending=[True,False])
#DataFrame 인덱스 기분 오른차순, 내림차순 정렬
df.sort_index(ascending=False)

     학년   학점     학과    동아리
이름
최지훈   4  3.9     의학   봉사활동
정소희   2  3.5    심리학   음악감상
이영희   2  3.8    경영학   독서토론
박민수   3  4.5   전자공학   로봇공학
김철수   1  4.2  컴퓨터공학  프로그래밍

## 6-5 실습 시나리오 - Kaggle을 활용한 데이터 수집 및 측정

- Kaggle([https://www.kaggle.com](https://www.kaggle.com)) 회원 가입
- Kaggle 접근 토큰 생성(API 키)

### Kaggle API 키 업로드

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"feel124","key":"06f8af822d964aeae974bb11a82cd985"}'}

### Kaggle API 키 사용을 위한 Colab 환경 설정

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

### Kaggle 데이터셋 다운로드

In [ ]:
!kaggle competitions download -c store-sales-time-series-forecasting

!unzip store-sales-time-series-forecasting.zip

Downloading store-sales-time-series-forecasting.zip to /content
100% 21.4M/21.4M [00:01<00:00, 13.1MB/s]

Archive:  store-sales-time-series-forecasting.zip
  inflating: holidays_events.csv
  inflating: oil.csv
  inflating: sample_submission.csv
  inflating: stores.csv
  inflating: test.csv
  inflating: train.csv
  inflating: transactions.csv

### Kaggle 데이터셋 DataFrame 로드 및 살펴보기

In [ ]:
import pandas as pd

# Grocery Sales 데이터 DataFrame 로드
train=pd.read_csv('train.csv')
stores=pd.read_csv('stores.csv')
transactions=pd.read_csv('transactions.csv')
oil=pd.read_csv('oil.csv')
holidays_events=pd.read_csv('holidays_events.csv')
# 판매 데이터 살펴보기
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

### Kaggle 데이터셋 측정

In [ ]:
# 판매 데이터 기본 통계량
train.describe()
# 매장 데이터 기본 정보
stores.head()
# 원유 가격 데이터 기본 정보
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20